language: ruby

before_install:
  - gem update bundler
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-gcc-4.6
bundler_args: --without development

rvm:
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - develop

script: bundle exec rake travis
